#spring.application.name=backend

spring:
  data:
    mongodb:
      uri: mongodb+srv://cookbook:cookbook1234@cluster-1.gmlwlcy.mongodb.net/
      database: cookbook
  # security:
  #   jwt:
  #     secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  #     expiration: 86400000

server:
  port: 8080
  servlet:
    context-path: /api